name: Deploy Documentation

on:
  push:
    branches:
      - main
    tags:
      - '*' # Trigger on any tag

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for mike to check out the underlying gh-pages history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-section-index \
            mkdocs-glightbox \
            mkdocs-minify-plugin \
            mkdocs-redirects \
            mkdocs-include-markdown-plugin \
            mkdocs-macros-plugin \
            mkdocs-table-reader-plugin \
            "mkdocstrings[python]" \
            mkdocs-swagger-ui-tag \
            pymdown-extensions \
            mike

      - name: Configure Git Environment
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy Versioned Site using Mike
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Extract the raw tag name
            RAW_TAG=${GITHUB_REF#refs/tags/}
            # Remove a leading 'v' if it exists (e.g., 'v1.0' -> '1.0')
            VERSION=${RAW_TAG#v}
            
            echo "Tag detected. Building Release Version: $VERSION"
            mike deploy --push --update-aliases $VERSION latest
            
          else
            echo "Branch detected. Building Rolling Edge version: main"
            mike deploy --push main
          fi